[package]
name = "project"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
dirs = "4.0"
anyhow = "1.0.100"
fs_extra ="1.3"
regex = "1"
walkdir = "2.5.0"
zip = "6.0.0"
chrono = "0.4.42"
